# -*- coding: utf-8 -*-
"""Data_Cleaning_Script.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wg4vr4tWUrn7fwE8kydVFmgNp8oGc4Kg
"""

"""
Career & Skill Demand Intelligence Platform
Data Preparation & Ingestion Script

Datasets:
    - O*NET Skills : Skills.xlsx
    - O*NET Occupations : Occupation_Data_BDA.xlsx
    - O*NET Education : Education.xlsx
    - BLS Wages (2024) : national_M2024_dl.xlsx

Outputs (saved to data/cleaned_data/):
    - skills_clean.csv
    - occupations_clean.csv
    - education_clean.csv
    - education_preferred.csv
    - wages_clean.csv
    - merged_career_dataset.csv
    - data_dictionary.csv  (also saved to docs/)
"""

import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

# CONFIG 
BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR   = os.path.abspath(os.path.join(BASE_DIR, "..", ".."))
INPUT_DIR  = os.path.join(ROOT_DIR, "data", "raw_data")
OUTPUT_DIR = os.path.join(ROOT_DIR, "data", "cleaned_data")
DOCS_DIR   = os.path.join(ROOT_DIR, "docs")

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(DOCS_DIR,   exist_ok=True)

print("  Career & Skill Demand Intelligence Platform")
print("  Data Preparation & Ingestion")
print(f"\nInput : {INPUT_DIR}")
print(f"Output : {OUTPUT_DIR}")

# EDUCATION LEVEL MAPPING (O*NET RL Scale)
EDUCATION_MAP = {
    1: "Less than High School",
    2: "High School Diploma or GED",
    3: "Post-Secondary Certificate",
    4: "Some College Courses",
    5: "Associate's Degree",
    6: "Bachelor's Degree",
    7: "Post-Baccalaureate Certificate",
    8: "Master's Degree",
    9: "Post-Master's Certificate",
    10: "First Professional Degree (e.g. JD, MD)",
    11: "Doctoral Degree",
    12: "Post-Doctoral Training"
}

# HELPER FUNCTIONS
def clean_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Lowercase + replace all non-alphanumeric chars with underscore."""
    df.columns = (
        df.columns
          .str.strip()
          .str.lower()
          .str.replace(r'[^a-z0-9]+', '_', regex=True)
          .str.strip('_')
    )
    return df

def standardize_soc(series: pd.Series) -> pd.Series:
    """Remove .00 suffix from O*NET SOC codes (e.g. 11-1011.00 -> 11-1011)."""
    return series.astype(str).str.replace(r'\.00$', '', regex=True).str.strip()


def summarize(df: pd.DataFrame, name: str):
    """Print a concise summary of a dataframe."""
    print(f"\n{'─'*55}")
    print(f"  {name}")
    print(f"{'─'*55}")
    print(f"  Shape  : {df.shape[0]:,} rows x {df.shape[1]} columns")
    null_counts = df.isnull().sum()
    null_cols   = null_counts[null_counts > 0]
    if len(null_cols):
        print(f"  Nulls  :")
        for col, cnt in null_cols.items():
            pct = cnt / len(df) * 100
            print(f"    {col:<35} {cnt:>7,}  ({pct:.1f}%)")
    else:
        print(f"  Nulls  : None")

# 1. LOAD DATASETS
print("\nLoading datasets ...")

skills_df = pd.read_excel(os.path.join(INPUT_DIR, "Skills.xlsx"))
occupations_df = pd.read_excel(os.path.join(INPUT_DIR, "Occupation_Data.xlsx"))
education_df = pd.read_excel(os.path.join(INPUT_DIR, "Education.xlsx"))
wages_df = pd.read_excel(os.path.join(INPUT_DIR, "national_M2024_dl.xlsx"))

print(f"Skills : {skills_df.shape}")
print(f"Occupations : {occupations_df.shape}")
print(f"Education : {education_df.shape}")
print(f"Wages (BLS) : {wages_df.shape}")

# 2. CLEAN COLUMN NAMES & STANDARDIZE SOC CODES
print("\nCleaning column names & standardizing SOC codes ...")

skills_df = clean_columns(skills_df.copy())
occupations_df = clean_columns(occupations_df.copy())
education_df = clean_columns(education_df.copy())
wages_df = clean_columns(wages_df.copy())

skills_df['soc_code'] = standardize_soc(skills_df['o_net_soc_code'])
occupations_df['soc_code'] = standardize_soc(occupations_df['o_net_soc_code'])
education_df['soc_code'] = standardize_soc(education_df['o_net_soc_code'])
wages_df['soc_code'] = wages_df['occ_code'].str.strip()

print("Done")

# 3. SELECT IMPORTANT COLUMNS & FIX DATA TYPES
print("\nSelecting important columns & fixing data types ...")

skills_clean = skills_df[[
    'soc_code', 'title', 'element_id', 'element_name',
    'scale_id', 'scale_name', 'data_value', 'date', 'domain_source'
]].copy()

occupations_clean = occupations_df[['soc_code', 'title', 'description']].copy()

education_clean = education_df[[
    'soc_code', 'title', 'element_name', 'scale_id',
    'category', 'data_value', 'recommend_suppress'
]].copy()

wages_clean = wages_df[[
    'soc_code', 'occ_title', 'o_group', 'tot_emp',
    'h_mean', 'a_mean', 'h_median', 'a_median'
]].copy()

# Fix BLS wage columns — convert suppression markers (# *) to NaN
wage_cols = ['h_mean', 'a_mean', 'h_median', 'a_median']
for col in wage_cols:
    wages_clean[col] = pd.to_numeric(
        wages_clean[col].astype(str)
            .str.replace(',', '')
            .str.strip()
            .replace({'#': np.nan, '*': np.nan}),
        errors='coerce'
    )
wages_clean['tot_emp'] = pd.to_numeric(
    wages_clean['tot_emp'].astype(str).str.replace(',', '').str.strip(),
    errors='coerce'
)

summarize(skills_clean,      "O*NET Skills (cleaned)")
summarize(occupations_clean, "O*NET Occupations (cleaned)")
summarize(education_clean,   "O*NET Education (cleaned)")
summarize(wages_clean,       "BLS Wages (cleaned)")

# 4. EXTRACT PREFERRED EDUCATION LEVEL PER OCCUPATION
print("\nExtracting preferred education level per occupation ...")

# Filter to Required Level of Education only, drop suppressed rows
edu_required = education_clean[
    (education_clean['element_name'] == 'Required Level of Education') &
    (education_clean['recommend_suppress'] != 'Y') &
    (education_clean['data_value'] > 0)
].copy()

# Pick category with highest data_value (most common level) per occupation
edu_preferred = (
    edu_required
    .sort_values('data_value', ascending=False)
    .drop_duplicates(subset='soc_code', keep='first')
    [['soc_code', 'category', 'data_value']]
    .rename(columns={
        'category'   : 'preferred_edu_category',
        'data_value' : 'preferred_edu_pct'
    })
    .copy()
)

# Map category number to readable label
edu_preferred['preferred_education'] = (
    edu_preferred['preferred_edu_category']
    .astype(int)
    .map(EDUCATION_MAP)
)

print(f"Education levels extracted: {edu_preferred.shape[0]:,} occupations")

# 5. MERGE ALL DATASETS
print("\nMerging datasets ...")

# Filter skills to Importance scale only (scale_id = 'IM')
skills_importance = skills_clean[skills_clean['scale_id'] == 'IM'].copy()

# Step 1: Skills + Occupation descriptions
skills_merged = pd.merge(
    skills_importance,
    occupations_clean[['soc_code', 'description']],
    on='soc_code',
    how='left'
)

# Step 2: Add preferred education level
skills_merged = pd.merge(
    skills_merged,
    edu_preferred[['soc_code', 'preferred_education', 'preferred_edu_pct']],
    on='soc_code',
    how='left'
)

# Step 3: Add BLS wages (detailed level only, match on 7-char SOC base)
wages_detail              = wages_clean[wages_clean['o_group'] == 'detailed'].copy()
wages_detail['soc_base']  = wages_detail['soc_code'].str[:7]
skills_merged['soc_base'] = skills_merged['soc_code'].str[:7]

career_dataset = pd.merge(
    skills_merged,
    wages_detail[['soc_base', 'tot_emp', 'a_mean', 'a_median']],
    on='soc_base',
    how='left'
).drop(columns='soc_base')

print(f"       Final career dataset : {career_dataset.shape[0]:,} rows x {career_dataset.shape[1]} columns")
print(f"       Wage match rate      : {career_dataset['a_mean'].notna().sum() / len(career_dataset) * 100:.1f}%")
print(f"       Education match rate : {career_dataset['preferred_education'].notna().sum() / len(career_dataset) * 100:.1f}%")

# DATA DICTIONARY
data_dict = pd.DataFrame({
    'dataset': [
        'skills_clean','skills_clean','skills_clean','skills_clean','skills_clean','skills_clean',
        'occupations_clean','occupations_clean','occupations_clean',
        'education_clean','education_clean','education_clean','education_clean',
        'edu_preferred','edu_preferred','edu_preferred',
        'wages_clean','wages_clean','wages_clean','wages_clean','wages_clean'
    ],
    'column': [
        'soc_code','title','element_name','scale_id','scale_name','data_value',
        'soc_code','title','description',
        'soc_code','element_name','category','data_value',
        'soc_code','preferred_education','preferred_edu_pct',
        'soc_code','occ_title','tot_emp','a_mean','a_median'
    ],
    'type': [
        'string','string','string','string','string','float',
        'string','string','string',
        'string','string','float','float',
        'string','string','float',
        'string','string','float','float','float'
    ],
    'description': [
        'SOC code — .00 suffix removed. Primary join key.',
        'Occupation title from O*NET',
        'Skill name (e.g. Reading Comprehension, Active Listening)',
        'IM = Importance scale, LV = Level scale',
        'Full scale name (Importance / Level)',
        'Skill score on 1-5 scale',
        'SOC code. Primary join key.',
        'Occupation title',
        'Detailed O*NET occupation description',
        'SOC code. Primary join key.',
        'Education element name (e.g. Required Level of Education)',
        'Education category number (1=Less than HS to 12=Post-Doctoral)',
        'Percentage of workers with that education level',
        'SOC code. Primary join key.',
        'Most common required education level label (from category 1-12 mapping)',
        'Percentage of workers who hold the preferred education level',
        'BLS SOC code (e.g. 11-1011)',
        'BLS occupation title',
        'Total national employment estimate (BLS 2024)',
        'Mean annual wage USD — suppressed values converted to NaN',
        'Median annual wage USD — suppressed values converted to NaN'
    ],
    'source': [
        'O*NET','O*NET','O*NET','O*NET','O*NET','O*NET',
        'O*NET','O*NET','O*NET',
        'O*NET','O*NET','O*NET','O*NET',
        'O*NET (derived)','O*NET (derived)','O*NET (derived)',
        'BLS','BLS','BLS','BLS','BLS'
    ]
})

# SAVE OUTPUTS
print("\nWriting cleaned files ...")

skills_clean.to_csv(os.path.join(OUTPUT_DIR,      "skills_clean.csv"),        index=False)
occupations_clean.to_csv(os.path.join(OUTPUT_DIR, "occupations_clean.csv"),   index=False)
education_clean.to_csv(os.path.join(OUTPUT_DIR,   "education_clean.csv"),     index=False)
edu_preferred.to_csv(os.path.join(OUTPUT_DIR,     "education_preferred.csv"), index=False)
wages_clean.to_csv(os.path.join(OUTPUT_DIR,       "wages_clean.csv"),          index=False)
career_dataset.to_csv(os.path.join(OUTPUT_DIR,    "merged_career_dataset.csv"),    index=False)
data_dict.to_csv(os.path.join(OUTPUT_DIR,         "data_dictionary.csv"),          index=False)
data_dict.to_csv(os.path.join(DOCS_DIR,           "data_dictionary.csv"),          index=False)

print(f"  skills_clean.csv          : {skills_clean.shape}")
print(f"  occupations_clean.csv     : {occupations_clean.shape}")
print(f"  education_clean.csv       : {education_clean.shape}")
print(f"  education_preferred.csv   : {edu_preferred.shape}")
print(f"  wages_clean.csv            : {wages_clean.shape}")
print(f"  merged_career_dataset.csv      : {career_dataset.shape}")
print(f"  data_dictionary.csv            : {data_dict.shape} (saved to cleaned_data/ and docs/)")

print("\nAll tasks complete")
print(f"  Output : {OUTPUT_DIR}")
